### ISSUE TITLE
Reintegrate small libraries

### ISSUE THREAD

**Issue by Sgoettschkes** [plumphp/plum#1]
Following up on your talk at ViennaPHP where you mentioned that you extracted smaller parts of plum to be reusable, I looked at plum, converted one of my importers to use plum (looks very promising) and also took a closer look at plum itself.

One thing that bothers me is your approach towards small libraries. I don't think this will work in the php community because of the culture and the versioning. I took a look at the other plum packages and they seem fairly redundant. Your CsvWriter for example could be replaced with https://github.com/keboola/php-csv. If you take a look at https://github.com/agileaddicts/cllctr/blob/e51f23ce53b57d5382dfe3361b640658a6e430a2/src/Cllctr/BackendBundle/DataProcessing/CsvReader.php, that's what I do. My reader is just a wrapper for Plum around Keboola, using their proven implementation of csv reading.
The same is true for your plum-console. It has hardcoded dependencies into Plum (`use Plum\Plum\Writer\WriterInterface`) and I don't see why anyone would use it without plum.

What do you (or others, for that matter), think?

**Comment by florianeckerstorfer** [comment]
Yes, the additional Plum packages will very often be only wrappers around native PHP functionality or other third party libraries. The latter case will cause some problems with the package management. 

Consider your `CsvReader` class. If we include this class in the main Plum package what do we do with the `keboola/php-csv`. Possibility 1 is to include in the `require` section of our `composer.json`. In this case the package will be downloaded for every user that uses Plum. No problem if we have one or two or three dependencies, but if in the future there exists a wide variety of readers, writers, filters and converters every user has to install dozens of dependencies she or he doesn't need. Space and time required to install these packages is annoying, but the breaker is that this can easily lead to conflicts in the package resolution. If Plum requires for a specific reader version X of a package, a user doesn't use this reader, but requires version y of the same package this will cause her or him major headaches. Thus, we can't add every third party package required by Plum in the `require` section.

The second possibility is to not include third party libraries in the `require` section, but only in the `require-dev` section. We don't have the problem with conflicting dependencies but the user needs to manually add the corresponding third-party libraries whenever she or he wants to use a component.

While users don't have a problem with massive downloading of dependencies developers still have the problem as does the build server.

In addition by using small modules each module can move at its own pace. For example, if we have to change one reader in a major way we can introduce a new major version of this component without BC breaking the whole library. Versioning of code is a lot, I am a lot lot easier when the code base is small. The only downside of using multiple packages is that there is some overhead while maintaining the library. But I figure the benefits (no package conflicts, fast dependency download, simpler versioning) are worth the overhead.

I agree that small libraries is not common in PHP, but I wish it was and maybe it will be in the future.

**Comment by Sgoettschkes** [comment]
Regarding require vs. require-dev: There is a third option: Don't require the package yourself but tell people in the documentation the dependencies of different readers/writers. One library that does this is [assetic](https://github.com/kriswallsmith/assetic). You have different Filters to choose from but many require additional installs, some of them php packages, some from other languages (ruby gems, npm modules).

I agree with the pace, though. This is an advantage of having small libraries.

For me, one of the things I really don't like about the node ecosystem are the small libraries. It feels like every package depends on 20 other packages and you are downloading half the internet when all you wanted to do was using one module. But I guess that's just personal preferences.

**Comment by florianeckerstorfer** [comment]
However, I still need to add them to `require-dev` so that the tests run through. The amount of libraries you use does not increase by a lot. A typical project will only use a very small subset of sub-packages. If Plum, at some point, may contain 20 readers, 20 writers, 15 filters and 30 converters it would be a lot more code to download than downloading the few component you actually require as separate packages.

Additionally a user doesn't have to worry about updates that much. With one big package a user would get very frequent updates with changes they actually don't require.

**Comment by Sgoettschkes** [comment]
I see your points. I'll give it a try and see how it works out. I just remembered that working with grunt and the various plugins from npm wasn't such a hassle after all, so I guess the "small packages" approach could work.
