### ISSUE TITLE
Adding additional Readers/Converters/Filters/Writers

### ISSUE THREAD

**Issue by Sgoettschkes** [plumphp/plum#2]
I'd like to know your take on adding additional Readers/Converters/Filters/Writers. Do you want to have many so everybody can start right away or do you want to keep the library "clean" and have people write their own?

For example, I have a Doctrine MongoDB writer which could be reused very easy: https://github.com/agileaddicts/cllctr/blob/e51f23ce53b57d5382dfe3361b640658a6e430a2/src/Cllctr/BackendBundle/DataProcessing/MongodbWriter.php
I also wrote a filter which uses the symfony validator: https://github.com/agileaddicts/cllctr/blob/e51f23ce53b57d5382dfe3361b640658a6e430a2/src/Cllctr/BackendBundle/DataProcessing/ValidatorFilter.php
Again, this could be very handy for people already using validators.

I'd be happy to prepare some PRs for such pipeline elements if you consider merging them. If, on the other hand, you'd like to keep the library small, I won't bother ;)

**Comment by florianeckerstorfer** [comment]
PRs would be great, but as mentioned in #1 I think that the benefits of small modules are worth the small overhead of maintaining more packages.

**Comment by Sgoettschkes** [comment]
I'll follow your lead, so small packages it is. How do you wanna do this? Me starting a small package and then transfering ownership to plumphp?

**Comment by florianeckerstorfer** [comment]
I don't have very much experience with this, but if you transfer the ownership to plumphp, you can still have admin/push rights to the repo, right? If so, yes.

**Comment by Sgoettschkes** [comment]
Me neither. How do projects like grunt organize these things? I am not familiar with this "small packages" approach and the only thing that comes to my mind which is similar are the grunt plugins I use. But I think they are organized through npm alone and grunt itself does not have ownership over the various plugins.

**Comment by Sgoettschkes** [comment]
After thinking about this a bit more, I think people maintaining their own packages (much like `grunt-contrib`) would be the way to go. Moving the ownership to plumphp might be the way for the most important ones but in that case plumphp take ownership.

By keeping a specific naming scheme like `plum-PACKAGENAME` it would be easy to find packages through composer.

I'll extract my validator into it's own package as a first testcase.

**Comment by florianeckerstorfer** [comment]
Yes, everyone can create their one packages using their own account. And since Composer has vendor namespaces we don't have to use the ugly `contrib` in the package name. Very basic packages (like validation) could also go in the "official" `plumphp` namespace, where I would help maintain them.
